Traceback (most recent call last):
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/jupyter_core/utils/__init__.py", line 173, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/mac/anaconda3/lib/python3.11/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
stocksymb='300339'
periods=['daily','weekly','monthly']
stockDict=plotDcStocks(stocksymb,periods)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mSSLError[0m                                  Traceback (most recent call last)
[0;31mSSLError[0m: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)

The above exception was the direct cause of the following exception:

[0;31mMaxRetryError[0m                             Traceback (most recent call last)
File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/adapters.py:486[0m, in [0;36mHTTPAdapter.send[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    485[0m [38;5;28;01mtry[39;00m:
[0;32m--> 486[0m     resp [38;5;241m=[39m conn[38;5;241m.[39murlopen(
[1;32m    487[0m         method[38;5;241m=[39mrequest[38;5;241m.[39mmethod,
[1;32m    488[0m         url[38;5;241m=[39murl,
[1;32m    489[0m         body[38;5;241m=[39mrequest[38;5;241m.[39mbody,
[1;32m    490[0m         headers[38;5;241m=[39mrequest[38;5;241m.[39mheaders,
[1;32m    491[0m         redirect[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    492[0m         assert_same_host[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    493[0m         preload_content[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    494[0m         decode_content[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    495[0m         retries[38;5;241m=[39m[38;5;28mself[39m[38;5;241m.[39mmax_retries,
[1;32m    496[0m         timeout[38;5;241m=[39mtimeout,
[1;32m    497[0m         chunked[38;5;241m=[39mchunked,
[1;32m    498[0m     )
[1;32m    500[0m [38;5;28;01mexcept[39;00m (ProtocolError, [38;5;167;01mOSError[39;00m) [38;5;28;01mas[39;00m err:

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/connectionpool.py:844[0m, in [0;36mHTTPConnectionPool.urlopen[0;34m(self, method, url, body, headers, retries, redirect, assert_same_host, timeout, pool_timeout, release_conn, chunked, body_pos, preload_content, decode_content, **response_kw)[0m
[1;32m    842[0m     new_e [38;5;241m=[39m ProtocolError([38;5;124m"[39m[38;5;124mConnection aborted.[39m[38;5;124m"[39m, new_e)
[0;32m--> 844[0m retries [38;5;241m=[39m retries[38;5;241m.[39mincrement(
[1;32m    845[0m     method, url, error[38;5;241m=[39mnew_e, _pool[38;5;241m=[39m[38;5;28mself[39m, _stacktrace[38;5;241m=[39msys[38;5;241m.[39mexc_info()[[38;5;241m2[39m]
[1;32m    846[0m )
[1;32m    847[0m retries[38;5;241m.[39msleep()

File [0;32m~/anaconda3/lib/python3.11/site-packages/urllib3/util/retry.py:515[0m, in [0;36mRetry.increment[0;34m(self, method, url, response, error, _pool, _stacktrace)[0m
[1;32m    514[0m     reason [38;5;241m=[39m error [38;5;129;01mor[39;00m ResponseError(cause)
[0;32m--> 515[0m     [38;5;28;01mraise[39;00m MaxRetryError(_pool, url, reason) [38;5;28;01mfrom[39;00m [38;5;21;01mreason[39;00m  [38;5;66;03m# type: ignore[arg-type][39;00m
[1;32m    517[0m log[38;5;241m.[39mdebug([38;5;124m"[39m[38;5;124mIncremented Retry for (url=[39m[38;5;124m'[39m[38;5;132;01m%s[39;00m[38;5;124m'[39m[38;5;124m): [39m[38;5;132;01m%r[39;00m[38;5;124m"[39m, url, new_retry)

[0;31mMaxRetryError[0m: HTTPSConnectionPool(host='80.push2delay.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=50000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A0+t%3A6%2Cm%3A0+t%3A80&fields=f12&_=1623833739532 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

[0;31mSSLError[0m                                  Traceback (most recent call last)
Cell [0;32mIn[28], line 3[0m
[1;32m      1[0m stocksymb[38;5;241m=[39m[38;5;124m'[39m[38;5;124m300339[39m[38;5;124m'[39m
[1;32m      2[0m periods[38;5;241m=[39m[[38;5;124m'[39m[38;5;124mdaily[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mweekly[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mmonthly[39m[38;5;124m'[39m]
[0;32m----> 3[0m stockDict[38;5;241m=[39mplotDcStocks(stocksymb,periods)

Cell [0;32mIn[27], line 4[0m, in [0;36mplotDcStocks[0;34m(stocksymb, periods)[0m
[1;32m      2[0m stockDict[38;5;241m=[39m{}
[1;32m      3[0m [38;5;28;01mfor[39;00m p [38;5;129;01min[39;00m periods:
[0;32m----> 4[0m     stockdf [38;5;241m=[39m ak[38;5;241m.[39mstock_zh_a_hist(symbol[38;5;241m=[39mstocksymb,period[38;5;241m=[39mp)
[1;32m      5[0m     stocknamedf[38;5;241m=[39mak[38;5;241m.[39mstock_individual_info_em(symbol[38;5;241m=[39mstocksymb)
[1;32m      6[0m     stockname[38;5;241m=[39mstocknamedf[38;5;241m.[39mloc[stocknamedf[[38;5;124m'[39m[38;5;124mitem[39m[38;5;124m'[39m][38;5;241m==[39m[38;5;124m'[39m[38;5;124m股票简称[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mvalue[39m[38;5;124m'[39m][[38;5;241m1[39m]

File [0;32m~/anaconda3/lib/python3.11/site-packages/akshare/stock_feature/stock_hist_em.py:1041[0m, in [0;36mstock_zh_a_hist[0;34m(symbol, period, start_date, end_date, adjust, timeout)[0m
[1;32m   1015[0m [38;5;28;01mdef[39;00m [38;5;21mstock_zh_a_hist[39m(
[1;32m   1016[0m     symbol: [38;5;28mstr[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124m000001[39m[38;5;124m"[39m,
[1;32m   1017[0m     period: [38;5;28mstr[39m [38;5;241m=[39m [38;5;124m"[39m[38;5;124mdaily[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m   1021[0m     timeout: [38;5;28mfloat[39m [38;5;241m=[39m [38;5;28;01mNone[39;00m,
[1;32m   1022[0m ) [38;5;241m-[39m[38;5;241m>[39m pd[38;5;241m.[39mDataFrame:
[1;32m   1023[0m [38;5;250m    [39m[38;5;124;03m"""[39;00m
[1;32m   1024[0m [38;5;124;03m    东方财富网-行情首页-沪深京 A 股-每日行情[39;00m
[1;32m   1025[0m [38;5;124;03m    https://quote.eastmoney.com/concept/sh603777.html?from=classic[39;00m
[0;32m   (...)[0m
[1;32m   1039[0m [38;5;124;03m    :rtype: pandas.DataFrame[39;00m
[1;32m   1040[0m [38;5;124;03m    """[39;00m
[0;32m-> 1041[0m     code_id_dict [38;5;241m=[39m code_id_map_em()
[1;32m   1042[0m     adjust_dict [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mqfq[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m1[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mhfq[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m2[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m0[39m[38;5;124m"[39m}
[1;32m   1043[0m     period_dict [38;5;241m=[39m {[38;5;124m"[39m[38;5;124mdaily[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m101[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mweekly[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m102[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124mmonthly[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m103[39m[38;5;124m"[39m}

File [0;32m~/anaconda3/lib/python3.11/site-packages/akshare/stock_feature/stock_hist_em.py:985[0m, in [0;36mcode_id_map_em[0;34m()[0m
[1;32m    971[0m code_id_dict [38;5;241m=[39m [38;5;28mdict[39m([38;5;28mzip[39m(temp_df[[38;5;124m"[39m[38;5;124msh_code[39m[38;5;124m"[39m], temp_df[[38;5;124m"[39m[38;5;124msh_id[39m[38;5;124m"[39m]))
[1;32m    972[0m params [38;5;241m=[39m {
[1;32m    973[0m     [38;5;124m"[39m[38;5;124mpn[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m1[39m[38;5;124m"[39m,
[1;32m    974[0m     [38;5;124m"[39m[38;5;124mpz[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m50000[39m[38;5;124m"[39m,
[0;32m   (...)[0m
[1;32m    983[0m     [38;5;124m"[39m[38;5;124m_[39m[38;5;124m"[39m: [38;5;124m"[39m[38;5;124m1623833739532[39m[38;5;124m"[39m,
[1;32m    984[0m }
[0;32m--> 985[0m r [38;5;241m=[39m requests[38;5;241m.[39mget(url, timeout[38;5;241m=[39m[38;5;241m15[39m, params[38;5;241m=[39mparams)
[1;32m    986[0m data_json [38;5;241m=[39m r[38;5;241m.[39mjson()
[1;32m    987[0m [38;5;28;01mif[39;00m [38;5;129;01mnot[39;00m data_json[[38;5;124m"[39m[38;5;124mdata[39m[38;5;124m"[39m][[38;5;124m"[39m[38;5;124mdiff[39m[38;5;124m"[39m]:

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/api.py:73[0m, in [0;36mget[0;34m(url, params, **kwargs)[0m
[1;32m     62[0m [38;5;28;01mdef[39;00m [38;5;21mget[39m(url, params[38;5;241m=[39m[38;5;28;01mNone[39;00m, [38;5;241m*[39m[38;5;241m*[39mkwargs):
[1;32m     63[0m [38;5;250m    [39m[38;5;124mr[39m[38;5;124;03m"""Sends a GET request.[39;00m
[1;32m     64[0m 
[1;32m     65[0m [38;5;124;03m    :param url: URL for the new :class:`Request` object.[39;00m
[0;32m   (...)[0m
[1;32m     70[0m [38;5;124;03m    :rtype: requests.Response[39;00m
[1;32m     71[0m [38;5;124;03m    """[39;00m
[0;32m---> 73[0m     [38;5;28;01mreturn[39;00m request([38;5;124m"[39m[38;5;124mget[39m[38;5;124m"[39m, url, params[38;5;241m=[39mparams, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/api.py:59[0m, in [0;36mrequest[0;34m(method, url, **kwargs)[0m
[1;32m     55[0m [38;5;66;03m# By using the 'with' statement we are sure the session is closed, thus we[39;00m
[1;32m     56[0m [38;5;66;03m# avoid leaving sockets open which can trigger a ResourceWarning in some[39;00m
[1;32m     57[0m [38;5;66;03m# cases, and look like a memory leak in others.[39;00m
[1;32m     58[0m [38;5;28;01mwith[39;00m sessions[38;5;241m.[39mSession() [38;5;28;01mas[39;00m session:
[0;32m---> 59[0m     [38;5;28;01mreturn[39;00m session[38;5;241m.[39mrequest(method[38;5;241m=[39mmethod, url[38;5;241m=[39murl, [38;5;241m*[39m[38;5;241m*[39mkwargs)

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:589[0m, in [0;36mSession.request[0;34m(self, method, url, params, data, headers, cookies, files, auth, timeout, allow_redirects, proxies, hooks, stream, verify, cert, json)[0m
[1;32m    584[0m send_kwargs [38;5;241m=[39m {
[1;32m    585[0m     [38;5;124m"[39m[38;5;124mtimeout[39m[38;5;124m"[39m: timeout,
[1;32m    586[0m     [38;5;124m"[39m[38;5;124mallow_redirects[39m[38;5;124m"[39m: allow_redirects,
[1;32m    587[0m }
[1;32m    588[0m send_kwargs[38;5;241m.[39mupdate(settings)
[0;32m--> 589[0m resp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msend(prep, [38;5;241m*[39m[38;5;241m*[39msend_kwargs)
[1;32m    591[0m [38;5;28;01mreturn[39;00m resp

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:725[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    722[0m [38;5;28;01mif[39;00m allow_redirects:
[1;32m    723[0m     [38;5;66;03m# Redirect resolving generator.[39;00m
[1;32m    724[0m     gen [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mresolve_redirects(r, request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 725[0m     history [38;5;241m=[39m [resp [38;5;28;01mfor[39;00m resp [38;5;129;01min[39;00m gen]
[1;32m    726[0m [38;5;28;01melse[39;00m:
[1;32m    727[0m     history [38;5;241m=[39m []

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:725[0m, in [0;36m<listcomp>[0;34m(.0)[0m
[1;32m    722[0m [38;5;28;01mif[39;00m allow_redirects:
[1;32m    723[0m     [38;5;66;03m# Redirect resolving generator.[39;00m
[1;32m    724[0m     gen [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39mresolve_redirects(r, request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[0;32m--> 725[0m     history [38;5;241m=[39m [resp [38;5;28;01mfor[39;00m resp [38;5;129;01min[39;00m gen]
[1;32m    726[0m [38;5;28;01melse[39;00m:
[1;32m    727[0m     history [38;5;241m=[39m []

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:266[0m, in [0;36mSessionRedirectMixin.resolve_redirects[0;34m(self, resp, req, stream, timeout, verify, cert, proxies, yield_requests, **adapter_kwargs)[0m
[1;32m    263[0m     [38;5;28;01myield[39;00m req
[1;32m    264[0m [38;5;28;01melse[39;00m:
[0;32m--> 266[0m     resp [38;5;241m=[39m [38;5;28mself[39m[38;5;241m.[39msend(
[1;32m    267[0m         req,
[1;32m    268[0m         stream[38;5;241m=[39mstream,
[1;32m    269[0m         timeout[38;5;241m=[39mtimeout,
[1;32m    270[0m         verify[38;5;241m=[39mverify,
[1;32m    271[0m         cert[38;5;241m=[39mcert,
[1;32m    272[0m         proxies[38;5;241m=[39mproxies,
[1;32m    273[0m         allow_redirects[38;5;241m=[39m[38;5;28;01mFalse[39;00m,
[1;32m    274[0m         [38;5;241m*[39m[38;5;241m*[39madapter_kwargs,
[1;32m    275[0m     )
[1;32m    277[0m     extract_cookies_to_jar([38;5;28mself[39m[38;5;241m.[39mcookies, prepared_request, resp[38;5;241m.[39mraw)
[1;32m    279[0m     [38;5;66;03m# extract redirect url, if any, for the next loop[39;00m

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/sessions.py:703[0m, in [0;36mSession.send[0;34m(self, request, **kwargs)[0m
[1;32m    700[0m start [38;5;241m=[39m preferred_clock()
[1;32m    702[0m [38;5;66;03m# Send the request[39;00m
[0;32m--> 703[0m r [38;5;241m=[39m adapter[38;5;241m.[39msend(request, [38;5;241m*[39m[38;5;241m*[39mkwargs)
[1;32m    705[0m [38;5;66;03m# Total elapsed time of the request (approximately)[39;00m
[1;32m    706[0m elapsed [38;5;241m=[39m preferred_clock() [38;5;241m-[39m start

File [0;32m~/anaconda3/lib/python3.11/site-packages/requests/adapters.py:517[0m, in [0;36mHTTPAdapter.send[0;34m(self, request, stream, timeout, verify, cert, proxies)[0m
[1;32m    513[0m         [38;5;28;01mraise[39;00m ProxyError(e, request[38;5;241m=[39mrequest)
[1;32m    515[0m     [38;5;28;01mif[39;00m [38;5;28misinstance[39m(e[38;5;241m.[39mreason, _SSLError):
[1;32m    516[0m         [38;5;66;03m# This branch is for urllib3 v1.22 and later.[39;00m
[0;32m--> 517[0m         [38;5;28;01mraise[39;00m SSLError(e, request[38;5;241m=[39mrequest)
[1;32m    519[0m     [38;5;28;01mraise[39;00m [38;5;167;01mConnectionError[39;00m(e, request[38;5;241m=[39mrequest)
[1;32m    521[0m [38;5;28;01mexcept[39;00m ClosedPoolError [38;5;28;01mas[39;00m e:

[0;31mSSLError[0m: HTTPSConnectionPool(host='80.push2delay.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/clist/get?pn=1&pz=50000&po=1&np=1&ut=bd1d9ddb04089700cf9c27f6f7426281&fltt=2&invt=2&fid=f3&fs=m%3A0+t%3A6%2Cm%3A0+t%3A80&fields=f12&_=1623833739532 (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

